---
title: "Chapter 5"
format: html
---

```{r}
library(ggplot2)
library(MASS)
```


Exercise 3:  

```{r}
# Bivariate Normal Distribution
mu <- c(5, 10)
Sigma <- matrix(c(1, .5,
                  .5, 1),
                nrow = 2, ncol = 2)

# sim data
X <- MASS::mvrnorm(n = 1000, mu = mu, Sigma = Sigma)
x1 <- X[, 1]
x2 <- X[, 2]

# Consider the conditional distribution of x2 given x1

# Numerically:
m <- lm(x2 ~ x1)
summary(m)
# conditional mean of x2|x2:
design <- model.matrix(~ x1)
beta <- matrix(m$coefficients, ncol = 1)
mean(design %*% beta)

# Analytically:
# conditional mean (expect mu[2]):
mean( mu[2] + (Sigma[1,2] * (1/Sigma[1,1])) * (x1 - mu[1]) )
# unexplained variance:
Sigma[2,2] - (Sigma[1,2]^2 / Sigma[1,1])

# lin reg coefficient
Sigma[1,2]/ Sigma[1,1]

# R^2 = cor(x1, x2)^2
Sigma[1,2]^2 / (Sigma[1,1] * Sigma[2,2])


# multivariate density
mvdnorm <- function(x, mu, Sigma) {
  p <- length(x)
  (1 / (2*pi))^(p/2) * det(Sigma)^(-1/2) * exp(
    (-1/2) * t(x - mu) %*% solve(Sigma) %*% (x - mu)
  )
}

## contour plot dataframe
n <- 50
dens <- data.frame(expand.grid(x1 = seq(min(x1), max(x1), length = n),
                               x2 = seq(min(x2), max(x2), length = n)))
dens$p <- vapply(1:nrow(dens),
                 \(i) mvdnorm(c(dens$x1[i], dens$x2[i]), mu, Sigma),
                 numeric(1))

ggplot() +
  geom_contour(data = dens,
               aes(x = x1, y = x2, z = p),
               color = "red",
               linewidth = 1) +
  geom_point(data = data.frame(x1 = x1, x2 = x2),
             aes(x = x1, y = x2),
             alpha = 0.35) +
  theme_bw()

```

